# Site
title:              Alex Coman
bio:                Hacker @RFC1392 / Python Developer / Security Adviser / Open-Source enthusiast
description:        "The personal website of Alex Coman."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/alexandru_coman.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false
locale:             en_US
url:                https://alexcoman.com
baseurl:            ''

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:

# Social
google:
  analytics:  UA-45303011-1

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - _site
  - src
  - vendor
  - CNAME
  - LICENSE
  - Rakefile

# Settings for deploy rake task
username:        alexcoman
repo:            alexcoman.com
branch:          source
relative_source: ../alexcoman.com/
destination:     ../alexcoman.com-pages/
production_url:  https://alexcoman.com
source_url:      https://github.com/alexcoman/alexcoman.com
