# General configuration
url: https://alexcoman.com
baseurl: ''
enforce_ssl: alexcoman.com
safe: true
lsi: false
sass:
    style: compressed

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

exclude:
  - .travis.yml
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - LICENSE

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/Alexandru_Coman.jpg"
  # author will appear under the avatar (optional)
  author: "Alex Coman"
  # tagline will appear under the title (optional)
  tagline: 'Python Developer / IT enthusiast<br>Cloud Engineer <a href="http://www.cloudbase.it/" target="_blank">@Cloudbase</a>'

  title: "Alex Coman"
  description: "The personal website of Alex Coman."
  keywords: "website, cloud, engineer, python, developer"

  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Settings for deploy rake task
username:        alexandrucoman
repo:            alexcoman.com
branch:          source
relative_source: ../alexcoman.com/
destination:     ../alexcoman.com-pages/
production_url:  https://alexcoman.com
source_url:      https://github.com/alexcoman/alexcoman.com
